### ISSUE TITLE
expand.land website reccomendations

### ISSUE THREAD

**Issue by JustAnotherUser19402** [ExpandTeam/expand-app#18]
~~AFAIK the Plesk server hosting the production copy of `expand-app` is down and returning nothing (no headers, content), less a problem with the repository and more a problem with the Plesk server.
The issue should be addressed soon - however, @Abrahamh08 is the only one with access to the Plesk server. Recommend we have a temporary backup of some sort for the future?~~

**The issue was addressed, however:**

Gwiddle seemed to be the cause of this issue, meaning our host may be unstable at some times. Perhaps we can decide on another hosting service, or have a backup in case the website goes down?

**Comment by Abrahamh08** [comment]
We are students with no funding. It is fine and people shouldn't expect a development website to have 100% up-time. When we release the production-ready website, it will be on a stable server, assuming our ICO is successful or we get enough support on Patreon.

**Comment by Abrahamh08** [comment]
Everything was moved to a digitalocean VPS that I manage.
