### ISSUE TITLE
Can't make posts

### ISSUE THREAD

**Issue by Bobbyblubbing** [ExpandTeam/expand-app#20]
-make a post
-post confirms
-does not show up in search
-(long post w/ images)

**Comment by JustAnotherUser19402** [comment]
Hi, @Bobbyblubbing - thanks for the issue. This issue has been classified as a bug and will be worked on promptly!

Can you please attach the `etherscan.io` link to your transaction? (for the post)
This will allow us to check if your transaction properly went through.

**Comment by Bobbyblubbing** [comment]
https://ropsten.etherscan.io/tx/0x2e8eb42f6ddfc28d419c0dc281274b7dbed49c918998f7b61447e8795778ce69

**Comment by JustAnotherUser19402** [comment]
Your transaction looks OK, but there are no new posts, this surely looks like a server-related issue that can't be fixed from here right now. (related to #21.) A fix will be released in the near future, for now - please try again later!

**Comment by Abrahamh08** [comment]
Afaik this is fixed now
