### ISSUE TITLE
Images in about section get clipped/overlap when the height of the window is too large.

### ISSUE THREAD

**Issue by 0e4ef622** [ExpandTeam/expand-app#7]
## Expected behavior
The images are sized reasonably such that no clipping nor overlapping occurs.

## Actual behavior
The images are too large to fit and thus overlap each other and get clipped by the header.

## Steps to reproduce
1. Size the window such `window.innerWidth = 847` and `window.innerHeight = 1596`.

## Screenshot
![image showing exaggerated clipping and overlapping](http://i.imgur.com/4THVkKN.png)

## Specifications
 - Browser: Chromium 68.0.3440.84
 - Platform: Arch Linux

**Comment by JustAnotherUser19402** [comment]
issue resolved - sorry about that. I put the website together in like 5 minutes for presentation day.

a much less "janky" version of the website will be coming by tomorrow, hopefully.

**Comment by JustAnotherUser19402** [comment]
See #8

**Comment by 0e4ef622** [comment]
mfw redundancy
