### ISSUE TITLE
Status page does not warn when logged out

### ISSUE THREAD

**Issue by JustAnotherUser19402** [ExpandTeam/expand-app#9]
It looks like in a new (Beta) release of Metamask, properties have changed making it undetectable (by our current means) to whether or not the user is logged out. The status bar is supposed to blink red when logged out, yet stays solid green.

**Comment by Abrahamh08** [comment]
This is not an issue with metamask, it comes from 6422172f0ed6955a4081fb05fccad865b1139975

**Comment by Abrahamh08** [comment]
Status will now warn when metamask and infura are unable to inject web3, meaning some services on the site will be unavailable. The status page should be redesigned to reflect this.

**Comment by JustAnotherUser19402** [comment]
Issue closed due to fundamental changes as stated above
